version: '2'
services:
  rs_rabbitmq:
    image: rabbitmq:3.6.5-management
    networks:
      - regards_IT_network

  rs_postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=azertyuiop123456789
      - POSTGRES_USER=azertyuiop123456789
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - regards_IT_network

  rs_build:
    image: 172.26.46.158/rs-maven
    environment:
      - BRANCH_NAME
      - WORKSPACE
      - CI_DIR
      - MODE
    volumes:
      - /DATA/maven-multibranch-repository:/localRepository
      - /usr/bin/docker:/bin/docker # link docker - only useful for deploy MODE
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.:/app_to_build
    links:
      - rs_rabbitmq
      - rs_postgres
    networks:
      - regards_IT_network

networks:
  regards_IT_network:
    external:
      name: regards_IT_network