# Variables for REGARDS Integration test

# Postgres
regards.IT.postgres.host=172.26.47.52
regards.IT.postgres.port=5432
regards.IT.postgres.database=rs_testdb_${user.name}
regards.IT.postgres.username=azertyuiop123456789
regards.IT.postgres.password=azertyuiop123456789

# ElasticSearch
regards.IT.elasticsearch.host=172.26.47.52
regards.IT.elasticsearch.port=9200

# RabbitMQ
regards.IT.rabbitmq.host=172.26.47.52
regards.IT.rabbitmq.port=5672
regards.IT.rabbitmq.management.host=172.26.47.52
regards.IT.rabbitmq.management.port=15672

# MinIO
regards.IT.minio.host=172.26.47.52
regards.IT.minio.port=9000
regards.IT.minio.protocol=http