#!/usr/bin/env groovy

/*
 * Copyright 2017-2022 CNES - CENTRE NATIONAL d'ETUDES SPATIALES
 *
 * This file is part of REGARDS.
 *
 * REGARDS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * REGARDS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with REGARDS. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Declarative Jenkinsfile. The language is Groovy.
 * Contains the definition of a Jenkins Pipeline, is checked into source control
 * and is expected to be the reference.
 * To fully support multibranch builds without issues, we are using docker-compose to setup cots for each build.
 *
 * @see https://jenkins.io/doc/book/pipeline/jenkinsfile/
 */

pipeline {
    options {
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '2'))
        disableConcurrentBuilds()
        parallelsAlwaysFailFast()
    }
    environment {
        PROJECT_NAME="${JOB_NAME}-${BUILD_NUMBER}"
        REGARDS_HOME="${WORKSPACE}"
        MVN_IMAGE="172.26.46.158/rs-maven-jdk8"
        BRANCH_NAME_VERSION="${BRANCH_NAME.replaceAll('[^A-Za-z0-9._-]', '')}-SNAPSHOT"
    }
    agent { label 'unix-integration' }
    stages {
        stage('Preparation') {
            steps {
                echo "Jenkins node name = ${env.NODE_NAME}"
                echo "Current workspace = ${env.WORKSPACE}"

                sh label: "Pull docker images", script: 'docker-compose -f ' + CI_DIR + '/docker/docker-compose-cots.yml pull \
                    && docker pull ' + MVN_IMAGE

                runMavenDockerImgWithoutCoTS("Build dependency tree", "dependencies")

                runMavenDockerImgWithoutCoTS("Build modules hashes", "hashes")
            }
        }
        stage("Fast Build") {
            steps {
                runMavenDockerImgWithoutCoTS("Build with docker profile", "compile")

                runMavenDockerImgWithoutCoTS("Build/Deploy docker images", "deployFastDockerImages")
            }
        }
        stage("Tests Preparation") {
            steps {
                sh label: "Launch COTS", script: 'docker-compose \
                        -f ' + CI_DIR + '/docker/docker-compose-cots.yml \
                        -p ' + PROJECT_NAME + ' \
                        up -d'
            }
        }

        stage('Run tests') {
            parallel {
                stage('-1-') {
                    stages {
                        // Please you use here the method [...]One (runMavenDockerImgParallelOne)
                        stage('Bom') {
                            steps {
                                runMavenDockerImgParallelOne("tests", "rs-bom")
                            }
                        }
                        stage('Microservice') {
                            steps {
                                runMavenDockerImgParallelOne("tests", "rs-microservice")
                            }
                        }
                        stage('Cloud') {
                            steps {
                                runMavenDockerImgParallelOne("tests", "rs-cloud")
                            }
                        }
                        stage('Ingest') {
                            steps {
                                runMavenDockerImgParallelOne("tests", "rs-ingest")
                            }
                        }
                        stage('Fem') {
                            steps {
                                runMavenDockerImgParallelOne("tests", "rs-fem")
                            }
                        }
                        stage('Worker manager') {
                            steps {
                                runMavenDockerImgParallelOne("tests", "rs-worker-manager")
                            }
                        }
                    }
                }
                stage('-2-') {
                    // Please you use here the method [...]Two (runMavenDockerImgParallelTwo)
                    stages {
                        stage('Admin') {
                            steps {
                                runMavenDockerImgParallelTwo("tests", "rs-admin")
                            }
                        }
                        stage('Dam') {
                            steps {
                                runMavenDockerImgParallelTwo("tests", "rs-dam")
                            }
                        }
                        stage('Catalog') {
                            steps {
                                runMavenDockerImgParallelTwo("tests", "rs-catalog")
                            }
                        }
                        stage('Access') {
                            steps {
                                runMavenDockerImgParallelTwo("tests", "rs-access")
                            }
                        }
                        stage('Notifier') {
                            steps {
                                runMavenDockerImgParallelTwo("tests", "rs-notifier")
                            }
                        }
                        stage('Storage') {
                            steps {
                                runMavenDockerImgParallelTwo("tests", "rs-storage")
                            }
                        }
                        stage('Dataprovider') {
                            steps {
                                runMavenDockerImgParallelTwo("tests", "rs-dataprovider")
                            }
                        }
                        stage('Order') {
                            steps {
                                runMavenDockerImgParallelTwo("tests", "rs-order")
                            }
                        }
                        stage('processing') {
                            steps {
                                runMavenDockerImgParallelTwo("tests", "rs-processing")
                            }
                        }
                    }
                }
            }
        }
        stage("Deploy artifacts") {
            when {
                branch pattern: /(master|develop.*|release.*)/, comparator: "REGEXP"
            }
            steps {
                runMavenDockerImgWithoutCoTS("Deploy Maven Artifacts", "deployMvnArtifacts")
            }
        }
        stage("Deploy Docker images") {
            steps {
                runMavenDockerImgWithoutCoTS("Build/Deploy stable docker images", "deployDockerImages")
            }
        }
    }
    post {
	    always {
            // Always send new successfull modules hashes to nexus
            runMavenDockerImgWithoutCoTS('POST-ALWAYS-TASK -- Send new successfull modules hashes to nexus', "updateHashes")
        }
        failure {
            tuleapNotifyCommitStatus status: 'failure', repositoryId: '875', credentialId: 'tuleap-ci-token'
            mattermostSend color: 'danger', message: "Build Failed - ${env.JOB_NAME}#${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)", text: "Changes: \n"+getChangeString()
            echo 'POST-FAILURE-TASK -- The build FAILED, let\'s print all COTS logs'

            // Log COTS only if they are existing
            sh label: "POST-FAILURE-TASK -- Print ElasticSearch logs", script: 'cd ' + CI_DIR + ' \
                 && if [ "$(docker-compose -f docker/docker-compose-cots.yml -p ' + PROJECT_NAME + ' ps | grep rs-elasticsearch)" ]; then \
                        echo "########################################" \
                     && echo "#### ELASTICSEARCH" \
                     && echo "########################################" \
                     && docker-compose -f docker/docker-compose-cots.yml -p ' + PROJECT_NAME + ' logs rs-elasticsearch; \
                   fi'

            sh label: "POST-FAILURE-TASK -- Print Postgres logs", script: 'cd ' + CI_DIR + ' \
                 && if [ "$(docker-compose -f docker/docker-compose-cots.yml -p ' + PROJECT_NAME + ' ps | grep rs-postgres)" ]; then \
                        echo "########################################" \
                     && echo "#### POSTGRES" \
                     && echo "########################################" \
                     && docker-compose -f docker/docker-compose-cots.yml -p ' + PROJECT_NAME + ' logs rs-postgres; \
                   fi'

            sh label: "POST-FAILURE-TASK -- Print First RabbitMQ logs", script: 'cd ' + CI_DIR + ' \
                 && if [ "$(docker-compose -f docker/docker-compose-cots.yml -p ' + PROJECT_NAME + ' ps | grep rs-rabbitmq-first)" ]; then \
                        echo "########################################" \
                     && echo "#### RABBITMQ" \
                     && echo "########################################" \
                     && docker-compose -f docker/docker-compose-cots.yml -p ' + PROJECT_NAME + ' logs rs-rabbitmq-first; \
                   fi'

            sh label: "POST-FAILURE-TASK -- Print Second RabbitMQ logs", script: 'cd ' + CI_DIR + ' \
                 && if [ "$(docker-compose -f docker/docker-compose-cots.yml -p ' + PROJECT_NAME + ' ps | grep rs-rabbitmq-second)" ]; then \
                        echo "########################################" \
                     && echo "#### RABBITMQ" \
                     && echo "########################################" \
                     && docker-compose -f docker/docker-compose-cots.yml -p ' + PROJECT_NAME + ' logs rs-rabbitmq-second; \
                   fi'
        }
        success {
            tuleapNotifyCommitStatus status: 'success', repositoryId: '875', credentialId: 'tuleap-ci-token'
        }
        cleanup {
            sh label: 'POST-CLEANUP-TASK -- Stop CoTs', script: 'docker-compose -f ' + CI_DIR + '/docker/docker-compose-cots.yml -p ' + PROJECT_NAME + ' down'
            sh label: 'POST-CLEANUP-TASK -- Rewrire owner and access rights, to avoid future build having files issues', script: 'chown -R jenkins:jenkins . \
                && chmod -R u+rwx . \
                && chmod -R g+rwx .'
        }
    }
}

@NonCPS
def getChangeString() {
    def changeString = ""

    echo "Gathering SCM changes"
    def changeLogSets = currentBuild.changeSets
    for (int i = 0; i < changeLogSets.size(); i++) {
        def entries = changeLogSets[i].items
        for (int j = 0; j < entries.length; j++) {
            def entry = entries[j]
            changeString += " - ${entry.msg} [@${entry.author}]\n"
        }
    }

    if (!changeString) {
        changeString = " - No new changes"
    }
    return changeString
}

// Return the shell to execute to run a docker container using rs-maven-ci image
// @params label Label to display on Blue Ocean
// @params mode Expected mode (see ci script file)
// @params regardsMs the pom submodule to restrict on
// @params isRequiringCots true when the container will use CoTs
// @params isRabbitMqIdFirst should use the first rabbitMQ
@NonCPS
def runMavenDockerImg(label, mode, regardsMs, isRequiringCots, isRabbitMqIdFirst) {
    // Transform PROJECT_NAME to what Docker will use for CoTS names
    // regards-oss-backend/feature%2Fimprove_jenkins_stages-31
    // become
    // regardsossbackendfeature2fimprovejenkinsstages31
    def dockerProject = PROJECT_NAME.replaceAll("[^a-zA-Z0-9]", "").toLowerCase()
    def dockerCommand = 'docker run --rm -i                                                          \
                        --name ' + dockerProject + '_maven_' + regardsMs + '                         \
                        -v ${WORKSPACE}:/app_to_build                                                \
                        -v /DATA/maven-multibranch-repository:/localRepository                       \
                        -v /usr/bin/docker:/bin/docker                                               \
                        -v /var/run/docker.sock:/var/run/docker.sock                                 \
                        -e BRANCH_NAME="${BRANCH_NAME}"                                              \
                        -e BRANCH_NAME_VERSION="${BRANCH_NAME_VERSION}"                              \
                        -e WORKSPACE="${WORKSPACE}"                                                  \
                        -e IGNORE_HASH="${IGNORE_HASH}"                                              \
                        -e CI_DIR="regards-ci/docker"                                                \
                        -e MODE="' + mode + '"                                                       \
                        -e REGARDS_HOME="${REGARDS_HOME}"                                            \
                        -e REGARDS_MS="' + regardsMs + '"                                            '
    if (isRequiringCots) {
        def rabbitMqId = isRabbitMqIdFirst ? 'first' : 'second'
        dockerCommand += '-e COTS="rs-elasticsearch:9300 rs-rabbitmq:5672 rs-postgres:5432"          \
                         --link ' + dockerProject + '_rs-rabbitmq-' + rabbitMqId + '_1:rs-rabbitmq   \
                         --link ' + dockerProject + '_rs-elasticsearch_1:rs-elasticsearch            \
                         --link ' + dockerProject + '_rs-postgres_1:rs-postgres                      '
    }
    dockerCommand +=    ' --network="regards_IT_network"                                             \
                        ' + MVN_IMAGE
    sh script: dockerCommand, label: label
}
// Use it when you don't need any COTS
def runMavenDockerImgWithoutCoTS(taskMainLabel, mode) {
    def label = taskMainLabel + " using maven container with mode=[" + mode + "]"
    runMavenDockerImg(label, mode, "", false, false)
}

// Use it when you want CoTS and you are the parallel "One"
def runMavenDockerImgParallelOne(mode, regardsMs) {
    def label = "Run " + mode + " on [" + regardsMs + "] using maven container. This tasks use CoTs and first RabbitMQ"
    runMavenDockerImg(label, mode, regardsMs, true, true)
}

// Use it when you want CoTS and you are the parallel "Two"
def runMavenDockerImgParallelTwo(mode, regardsMs) {
    def label = "Run " + mode + " on [" + regardsMs + "] using maven container. This tasks use CoTs and second RabbitMQ"
    runMavenDockerImg(label, mode, regardsMs, true, false)
}
