#!/usr/bin/env groovy

/*
 * LICENSE_PLACEHOLDER
 */

/**
 * Declarative Jenkinsfile. The language is Groovy.
 * Contains the definition of a Jenkins Pipeline, is checked into source control
 * and is expected to be the reference.
 * To fully support multibranch builds without issues, we are using docker-compose to setup cots for each build.
 *
 * @see https://jenkins.io/doc/book/pipeline/jenkinsfile/
 */

pipeline {
    options {
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '2'))
        disableConcurrentBuilds()
    }
    environment {
        PROJECT_NAME="${JOB_NAME}-${BUILD_NUMBER}"
        REGARDS_HOME="${WORKSPACE}"
    }
    agent { label 'unix-integration' }
    stages {
        // Refresh docker images
        stage('Pull docker images') {
            steps {
                sh 'cd ' + CI_DIR + ' \
                     && docker-compose -f docker/docker-compose.yml pull'
            }
        }
        stage("Verifying git branch") {
            when {
                not {
                    branch pattern: /(master|develop.*|release.*)/, comparator: "REGEXP"
                }
            }
            environment {
                REGARDS_VERSION="${BRANCH_NAME.replaceAll('[^A-Za-z0-9._-]', '')}-SNAPSHOT"
                MODE="install"
            }
            steps {
                sh 'cd ' + CI_DIR + ' \
                     && docker-compose \
                            -f docker/docker-compose.yml \
                            -p ' + PROJECT_NAME + ' \
                            up \
                            --exit-code-from rs-build \
                            --abort-on-container-exit \
                            rs-build'
            }
        }
        stage("Deploy and (Docker) Tag git branch") {
            when {
                branch pattern: /(master|develop.*|release.*)/, comparator: "REGEXP"
            }
            environment {
                MODE="deploy"
            }
            steps {
                sh 'printenv'
                sh 'cd ' + CI_DIR + ' \
                     && docker-compose \
                            -f docker/docker-compose.yml \
                            -p ' + PROJECT_NAME + ' \
                            up \
                            --exit-code-from rs-build \
                            --abort-on-container-exit \
                            rs-build'
            }
        }
    }
    post {
        failure {
            tuleapNotifyCommitStatus status: 'failure', repositoryId: '875', credentialId: 'tuleap-ci-token'
            mattermostSend color: 'danger', message: "Build Failed - ${env.JOB_NAME}#${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)", text: "Changes: \n"+getChangeString()
            echo 'The build FAILED, let\'s print all COTS logs'

            // Log COTS only if they are existing
            sh 'cd ' + CI_DIR + ' \
                 && if [ "$(docker-compose -f docker/docker-compose.yml -p ' + PROJECT_NAME + ' ps | grep rs-elasticsearch)" ]; then \
                        echo "########################################" \
                     && echo "#### ELASTICSEARCH" \
                     && echo "########################################" \
                     && docker-compose -f docker/docker-compose.yml -p ' + PROJECT_NAME + ' logs rs-elasticsearch; \
                   fi'


            sh 'cd ' + CI_DIR + ' \
                 && if [ "$(docker-compose -f docker/docker-compose.yml -p ' + PROJECT_NAME + ' ps | grep rs-postgres)" ]; then \
                        echo "########################################" \
                     && echo "#### POSTGRES" \
                     && echo "########################################" \
                     && docker-compose -f docker/docker-compose.yml -p ' + PROJECT_NAME + ' logs rs-postgres; \
                   fi'


            sh 'cd ' + CI_DIR + ' \
                 && if [ "$(docker-compose -f docker/docker-compose.yml -p ' + PROJECT_NAME + ' ps | grep rs-rabbitmq)" ]; then \
                        echo "########################################" \
                     && echo "#### RABBITMQ" \
                     && echo "########################################" \
                     && docker-compose -f docker/docker-compose.yml -p ' + PROJECT_NAME + ' logs rs-rabbitmq; \
                   fi'
        }
        success {
            tuleapNotifyCommitStatus status: 'success', repositoryId: '875', credentialId: 'tuleap-ci-token'
        }
        cleanup {
            echo 'lets clean up the mess!'
            sh 'cd ' + CI_DIR + ' \
                 && docker-compose -f docker/docker-compose.yml -p ' + PROJECT_NAME + ' down'
            echo 'In case any test played with access rights, lets add read/write to owner'
            sh 'chmod -R +rw .'
        }
    }
}

@NonCPS
def getChangeString() {
    def changeString = ""

    echo "Gathering SCM changes"
    def changeLogSets = currentBuild.changeSets
    for (int i = 0; i < changeLogSets.size(); i++) {
        def entries = changeLogSets[i].items
        for (int j = 0; j < entries.length; j++) {
            def entry = entries[j]
            changeString += " - ${entry.msg} [@${entry.author}]\n"
        }
    }

    if (!changeString) {
        changeString = " - No new changes"
    }
    return changeString
}
