#!/usr/bin/env bash

SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Allow piping through tee to forward exit statuses
set -o pipefail

source ${SCRIPTS}/utils
source ${SCRIPTS}/variables
source ${SCRIPTS}/hash
source ${SCRIPTS}/build

STEP=$1

mkdir -p ${DATADIR}

echo "#####################################"
echo "#        ---  REGARDS CI ---        #"
echo "#####################################"

cd ${SERVICES} || exit
case $STEP in
    dependencies)
        tm dependencyTree
    ;;
    hashes)
        tm computeModuleHashes
    ;;
    compile)
        tm compile
    ;;
    tests)
	    tm tests "false"
    ;;
    sonarTests)
	    tm tests "true"
    ;;
    deployDockerImages)
        tm buildAnDeployDockerImages
    ;;
    deployFastDockerImages)
        tm buildAnDeployDockerImages "fast-" 
    ;;
    deployMvnArtifacts)
        tm deployMvnArtifacts
    ;;
    updateHashes)
        tm updateNexusHashes
    ;;
  #TODO Improve hash (get git diff since last build success' commit, assoc files to modules, only hash those)
  #TODO Build docs site
    *)
        echo -e "Unknown step '$STEP'. Available steps:
        \n- dependencies
        \n- hashes
        \n- compile
        \n- compileForTests
        \n- tests
        \n- deployDockerImages
        \n- deployFastDockerImages
        \n- deployMvnArtifacts
        \n- updateHashes
        \n- nightly
        "
    ;;
esac

echo "######################################"
echo "#           ---  END ---             #"
echo "######################################"



