#! /usr/bin/env bash

function tm {
  s=$(date +%s)
  "$@"
  echo "...took $(($(date +%s)-s)) seconds." >&2
}

function failCheck {
    exit_status=$1
    if [[ ${exit_status} != 0 ]]; then
        echo ERRROR "${exit_status}"
        exit "${exit_status}"
    fi
}
