#!/usr/bin/env bash

NEXUS_DEPLOY_USER="admin"
NEXUS_DEPLOY_PASSWORD="password"
NEXUS_BASE="https://172.26.46.158:8443"
NEXUS_RAW="${NEXUS_BASE}/repository/regards-raw"
MAVEN_REPOSITORY="maven-snapshot-regards"
SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
SERVICES=${SERVICES:-$(realpath ${SCRIPTS}/../..)}
DATADIR=${SCRIPTS}/data
JOB_ID=${JOB_ID:=local}

if [ ${BRANCH_NAME} == "develop" ] || [[ ${BRANCH_NAME} =~ "release/" ]]; then
    REGARDS_VERSION=$(cat ${SERVICES}/pom.xml | grep '<regards.version>' | cut -d '>' -f2 | cut -d '<' -f1)
fi
if [[ ${BRANCH_NAME} =~ "feature/" ]] || [[ ${BRANCH_NAME} =~ "hotfix/" ]]; then
    REGARDS_VERSION="${BRANCH_NAME_VERSION}"
fi
if [ ${BRANCH_NAME} == "master" ]; then
    REGARDS_VERSION="master"
fi

if [ -z ${REGARDS_VERSION} ]; then
    echo "Error calculating REGARDS VERSION for branch ${BRANCH_NAME}"
    exit 1
fi



