version: '2'
services:
  rs-rabbitmq:
    image: 172.26.46.158/regards-messaging:latest
    networks:
      - regards_IT_network

  rs-postgres:
    image: 172.26.46.158/regards-database:latest
    environment:
      - POSTGRES_PASSWORD=azertyuiop123456789
      - POSTGRES_USER=azertyuiop123456789
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - regards_IT_network

  rs-elasticsearch:
    image: 172.26.46.158/regards-elasticsearch:latest
    environment:
      - cluster.name=regards
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2500m -Xmx2500m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - regards_IT_network

  rs-build:
    image: 172.26.46.158/rs-maven-ci
    environment:
      - BRANCH_NAME
      - JOB_NAME
      - BUILD_TAG
      - GIT_COMMIT
      - TAG_NAME
      - WORKSPACE
      - CI_DIR=regards-ci/docker
      - MODE
      - REGARDS_HOME
      - COTS=rs-elasticsearch:9300 rs-rabbitmq:5672 rs-postgres:5432
    volumes:
      - /DATA/maven-multibranch-repository:/localRepository
      - /usr/bin/docker:/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../.:/app_to_build
    links:
      - rs-rabbitmq
      - rs-postgres
      - rs-elasticsearch
    networks:
      - regards_IT_network

networks:
  regards_IT_network:
    external:
      name: regards_IT_network
