package fr.cnes.regards.modules.processing.events;

import fr.cnes.regards.framework.amqp.event.Event;
import fr.cnes.regards.framework.amqp.event.ISubscribable;
import fr.cnes.regards.framework.amqp.event.JsonMessageConverter;
import fr.cnes.regards.framework.amqp.event.Target;
import fr.cnes.regards.modules.processing.domain.execution.ExecutionStatus;
import fr.cnes.regards.modules.processing.dto.POutputFileDTO;
import io.vavr.collection.Seq;
import lombok.*;

import java.net.URL;
import java.util.UUID;

@Event(target = Target.ONE_PER_MICROSERVICE_TYPE, converter = JsonMessageConverter.GSON)
@Value @With
public class PExecutionResultEvent implements ISubscribable {

    /** The execution this message was related to. */
    UUID executionId;

    /** The batch the execution this message was related to was related to. */
    UUID batchId;

    ExecutionStatus finalStatus;

    /** Used in case of success, the links to the resulting files generated by the execution. */
    Seq<POutputFileDTO> outputs;

    /** Used in case of failure, to provide context for the failure. */
    Seq<String> messages;

}
