drop table ta_notification_projectuser;
drop table ta_notification_role;
drop table t_notification;
drop table t_notification_settings;
create table t_notification (id int8 not null, date timestamp, message varchar(255), sender varchar(255), status varchar(255), type varchar(255), title varchar(255), primary key (id));
create table t_notification_settings (id int8 not null, days int4, frequency varchar(255), hours int4, user_id int8, primary key (id));
create table ta_notification_projectuser (notification_id int8 not null, projectuser_id int8 not null);
create table ta_notification_role (notification_id int8 not null, role_id int8 not null);
alter table t_notification_settings add constraint fk_notification_settings_user foreign key (user_id) references t_project_user;
alter table ta_notification_projectuser add constraint fk_projectuser_notification foreign key (projectuser_id) references t_project_user;
alter table ta_notification_projectuser add constraint fk_notification_projectuser foreign key (notification_id) references t_notification;
alter table ta_notification_role add constraint fk_role_notification foreign key (role_id) references t_role;
alter table ta_notification_role add constraint fk_notification_role foreign key (notification_id) references t_notification;