server:
  adress: localhost
  port: 3333

security:
  client: acme
  secret: acmesecret

spring:
  application:
    name : access
    
swagger:
  api:
    name: access-api

cloud:
  config:
    discovery:
      enabled: false
    server:
      enabled: false
      name: myconfigserver
      
eureka:
  client:
    enabled: false

 
