# Service Registry
service:
  registry:
    port: 8761

# Logger
logging:
  level:
    regards: DEBUG
    
jwt:
  secret: 123456789
  
spring:
  jpa:
    hibernate:
      ddl-auto: update

#Actuator properties
endpoints:
  shutdown:
    enabled : true