create table t_acq_file_info (id int8 not null, comment text, data_type varchar(16), lastModificationDate timestamp, mandatory boolean, mime_type varchar(255), scan_conf_id int8 not null, acq_chain_id int8, primary key (id));
create table t_acq_processing_chain (id int8 not null, active boolean, datasetIpId varchar(256), ingest_chain varchar(255), label varchar(64) not null, last_activation_date timestamp, mode varchar(16), period int8, running boolean not null, generatesip_conf_id int8, postprocesssip_conf_id int8, product_conf_id int8, session varchar(50), validation_conf_id int8, primary key (id));
create table t_acquisition_exec_chain (id int8 not null, session varchar(255), start_date timestamp, stop_date timestamp, chain_id int8, primary key (id));
create table t_acquisition_file (id int8 not null, acquisition_date timestamp, checksum varchar(255), checksumAlgorithm varchar(16), error varchar(256), filePath varchar(255), state varchar(16), acq_file_info_id int8, product_id int8, primary key (id));
create table t_acquisition_product (id int8 not null, ip_id varchar(128), last_update timestamp not null, product_name varchar(128), session varchar(128), json_sip jsonb, sip_state varchar(32) not null, product_state varchar(32) not null, processing_chain_id int8, primary key (id));
create index idx_acq_exec_session on t_acquisition_exec_chain (session);
alter table t_acquisition_exec_chain add constraint uk_acq_exec_session unique (session);
create index idx_acq_processing_chain on t_acquisition_product (processing_chain_id);
create index idx_acq_product_name on t_acquisition_product (product_name);
create index idx_acq_product_sip_state on t_acquisition_product (sip_state);
create index idx_acq_product_state on t_acquisition_product (product_state);
alter table t_acquisition_product add constraint uk_acq_product_ipId unique (ip_id);
alter table t_acquisition_product add constraint uk_acq_product_name unique (product_name);
create sequence seq_acq_chain start 1 increment 50;
create sequence seq_acq_file start 1 increment 50;
create sequence seq_acq_file_info start 1 increment 50;
create sequence seq_exec_chain start 1 increment 50;
create sequence seq_product start 1 increment 50;
alter table t_acq_file_info add constraint fk_scan_conf_id foreign key (scan_conf_id) references t_plugin_configuration;
alter table t_acq_file_info add constraint fk_acq_chain_id foreign key (acq_chain_id) references t_acq_processing_chain;
alter table t_acq_processing_chain add constraint fk_generatesip_conf_id foreign key (generatesip_conf_id) references t_plugin_configuration;
alter table t_acq_processing_chain add constraint fk_postprocesssip_conf_id foreign key (postprocesssip_conf_id) references t_plugin_configuration;
alter table t_acq_processing_chain add constraint fk_product_conf_id foreign key (product_conf_id) references t_plugin_configuration;
alter table t_acq_processing_chain add constraint fk_validation_conf_id foreign key (validation_conf_id) references t_plugin_configuration;
alter table t_acquisition_exec_chain add constraint fk_acq_exec_chain_id foreign key (chain_id) references t_acq_processing_chain;
alter table t_acquisition_file add constraint fk_acq_file_info_id foreign key (acq_file_info_id) references t_acq_file_info;
alter table t_acquisition_file add constraint fk_product_id foreign key (product_id) references t_acquisition_product;
alter table t_acquisition_product add constraint fk_processing_chain_id foreign key (processing_chain_id) references t_acq_processing_chain;
