create table t_cache_file (id int8 not null, checksum varchar(128), expiration_date timestamp, file_size int8, last_request_date timestamp, location varchar(255), primary key (id));
create table t_file_deletion_request (file_reference int8 not null, error_cause varchar(512), force_delete boolean, status varchar(255) not null, storage varchar(128) not null, primary key (file_reference));
create table t_file_reference (id int8 not null, storage varchar(128), url varchar(2048), algorithm varchar(16) not null, checksum varchar(128) not null, fileName varchar(256) not null, fileSize int8, height int4, mime_type varchar(255) not null, type varchar(256), width int4, storageDate timestamp, primary key (id));
create table t_file_cache_request (id int8 not null, error_cause varchar(512), checksum varchar(128) not null, storage varchar(128) not null, destination_path varchar(2048) not null,file_size int8 not null, expiration_date timestamp,status varchar(255) not null, file_ref_id int8 not null, primary key (id));
create table t_file_storage_request (id int8 not null, storage varchar(255), storage_subdirectory varchar(2048), error_cause varchar(512), algorithm varchar(16) not null, checksum varchar(128) not null, fileName varchar(256) not null, fileSize int8, height int4, mime_type varchar(255) not null, type varchar(256), width int4, origin_url varchar(2048), status varchar(255) not null, primary key (id));
create table t_prioritized_storage (storage_conf_id int8 not null, priority int8, storage_type varchar(255), primary key (storage_conf_id));
create table t_storage_location (id int8 not null, allowed_size int8, last_update_date timestamp, name varchar(128), nb_ref_files int8, total_size int8, primary key (id));
create table t_storage_monitoring (id int8 not null, last_file_reference_id int8, last_monitoring_date timestamp, last_monitoring_duration int8, running boolean not null, primary key (id));
create table ta_file_ref_owners (file_ref_id int8 not null, owner varchar(255));
create table ta_file_storage_request_owners (file_ref_id int8 not null, owner varchar(255));
create index idx_cache_file_checksum on t_cache_file (checksum);
alter table t_cache_file add constraint uk_cache_file_checksum unique (checksum);
create index idx_file_deletion_request on t_file_deletion_request (storage);
create index idx_file_reference on t_file_reference (storage, checksum);
create index idx_file_reference_checksum on t_file_reference (checksum);
alter table t_file_reference add constraint uk_t_file_reference_checksum_storage unique (checksum, storage);
create index idx_file_storage_request on t_file_storage_request (storage, checksum);
alter table t_file_storage_request add constraint t_file_storage_request_checksum_storage unique (checksum, storage);
alter table t_prioritized_storage add constraint uk_priotitized_storage unique (storage_type, priority);
create index idx_storage_location on t_storage_location (name);
alter table t_storage_location add constraint uk_t_storage_location_name unique (name);
alter table t_file_cache_request add constraint uk_t_file_cache_request_checksum unique (checksum);
create sequence seq_cache_file start 1 increment 50;
create sequence seq_file_reference start 1 increment 50;
create sequence seq_file_cache_request start 1 increment 50;
create sequence seq_file_storage_request start 1 increment 50;
create sequence seq_storage_location start 1 increment 50;
alter table t_file_deletion_request add constraint FK8iyuxn10e6gx9ybs6i92mxdgq foreign key (file_reference) references t_file_reference;
alter table t_file_cache_request add constraint FKfrr17d4xaxdk88c59ne2nkbi7 foreign key (file_ref_id) references t_file_reference;
alter table t_prioritized_storage add constraint FKj8h3r7gds36k6uvtequf2d5p foreign key (storage_conf_id) references t_plugin_configuration;
alter table ta_file_ref_owners add constraint fk_ta_file_ref_owners_t_file_reference foreign key (file_ref_id) references t_file_reference;
alter table ta_file_storage_request_owners add constraint fk_ta_file_storage_request_owners_t_file_storage_request foreign key (file_ref_id) references t_file_storage_request;
