create table t_cache_file (id int8 not null, checksum varchar(128), expiration_date timestamp, file_size int8, location varchar(255), primary key (id));
create table t_file_cache_request (id int8 not null, checksum varchar(128) not null, destination_path varchar(2048) not null, error_cause varchar(512), expiration_date timestamp, file_size int8 not null, group_id varchar(128) not null, status varchar(255) not null, storage varchar(128) not null, file_ref_id int8 not null, primary key (id));
create table t_file_copy_request (id int8 not null, error_cause varchar(512), cache_group_id varchar(128), storage_group_id varchar(128), group_id varchar(128) not null, algorithm varchar(16) not null, checksum varchar(128) not null, fileName varchar(256) not null, fileSize int8, height int4, mime_type varchar(255) not null, type varchar(256), width int4, status varchar(255) not null, storage varchar(128), storage_subdirectory varchar(2048), primary key (id));
create table t_file_deletion_request (file_reference int8 not null, error_cause varchar(512), force_delete boolean, group_id varchar(128) not null, status varchar(255) not null, storage varchar(128) not null, primary key (file_reference));
create table t_file_reference (id int8 not null, storage varchar(128), url varchar(2048), algorithm varchar(16) not null, checksum varchar(128) not null, fileName varchar(256) not null, fileSize int8, height int4, mime_type varchar(255) not null, type varchar(256), width int4, storageDate timestamp, primary key (id));
create table t_file_storage_request (id int8 not null, error_cause varchar(512), algorithm varchar(16) not null, checksum varchar(128) not null, fileName varchar(256) not null, fileSize int8, height int4, mime_type varchar(255) not null, type varchar(256), width int4, origin_url varchar(2048), status varchar(255) not null, storage varchar(128), storage_subdirectory varchar(2048), primary key (id));
create table t_prioritized_storage (storage_conf_id int8 not null, priority int8, storage_type varchar(255), primary key (storage_conf_id));
create table t_storage_location (id int8 not null, allowed_size int8, last_update_date timestamp, name varchar(128), nb_ref_files int8, total_size int8, primary key (id));
create table t_storage_monitoring_process (id int8 not null, last_file_reference_id int8, last_monitoring_date timestamp, last_monitoring_duration int8, running boolean not null, primary key (id));
create table ta_cache_file_group_ids (cache_file_id int8 not null, group_id varchar(128) not null, primary key (cache_file_id, group_id));
create table ta_file_ref_owners (file_ref_id int8 not null, owner varchar(255));
create table ta_file_storage_request_owners (file_storage_request_id int8 not null, owner varchar(255));
create table ta_storage_request_group_ids (file_storage_request_id int8 not null, group_id varchar(128) not null, primary key (file_storage_request_id, group_id));
create index idx_cache_file_checksum on t_cache_file (checksum);
alter table t_cache_file add constraint uk_cache_file_checksum unique (checksum);
create index idx_file_cache_request_grp on t_file_cache_request (group_id);
create index idx_file_cache_request_cs on t_file_cache_request (checksum);
create index idx_file_cache_request_storage on t_file_cache_request (storage);
alter table t_file_cache_request add constraint uk_t_file_cache_request_checksum unique (checksum);
create index idx_file_copy_request on t_file_copy_request (storage, checksum);
create index idx_file_copy_request_grp on t_file_copy_request (group_id);
create index idx_file_copy_request_cache_grp on t_file_copy_request (cache_group_id);
create index idx_file_copy_request_storage_grp on t_file_copy_request (storage_group_id);
alter table t_file_copy_request add constraint t_file_copy_request_checksum_storage unique (checksum, storage);
create index idx_file_deletion_request on t_file_deletion_request (storage);
create index idx_file_deletion_grp on t_file_deletion_request (group_id);
create index idx_file_reference on t_file_reference (storage, checksum);
alter table t_file_reference add constraint uk_t_file_reference_checksum_storage unique (checksum, storage);
create index idx_file_storage_request on t_file_storage_request (storage, checksum);
create index idx_file_storage_request_cs on t_file_storage_request (checksum);
create index idx_file_storage_request_storage on t_file_storage_request (storage);
alter table t_file_storage_request add constraint t_file_storage_request_checksum_storage unique (checksum, storage);
alter table t_prioritized_storage add constraint uk_priotitized_storage unique (storage_type, priority);
create index idx_storage_location on t_storage_location (name);
alter table t_storage_location add constraint uk_t_storage_location_name unique (name);
create sequence seq_cache_file start 1 increment 50;
create sequence seq_file_cache_request start 1 increment 50;
create sequence seq_file_reference start 1 increment 50;
create sequence seq_file_storage_request start 1 increment 50;
create sequence seq_storage_location start 1 increment 50;
alter table t_file_cache_request add constraint FKmhrrlwenlm8bmtwy5laku0jvu foreign key (file_ref_id) references t_file_reference;
alter table t_file_deletion_request add constraint FK8iyuxn10e6gx9ybs6i92mxdgq foreign key (file_reference) references t_file_reference;
alter table t_prioritized_storage add constraint FKj8h3r7gds36k6uvtequf2d5p foreign key (storage_conf_id) references t_plugin_configuration;
alter table ta_cache_file_group_ids add constraint fk_ta_cache_file_request_ids_t_file_cache foreign key (cache_file_id) references t_cache_file;
alter table ta_file_ref_owners add constraint fk_ta_file_ref_owners_t_file_reference foreign key (file_ref_id) references t_file_reference;
alter table ta_file_storage_request_owners add constraint fk_ta_file_storage_request_owners_t_file_storage_request foreign key (file_storage_request_id) references t_file_storage_request;
alter table ta_storage_request_group_ids add constraint fk_ta_storage_request_group_ids_t_file_storage_request foreign key (file_storage_request_id) references t_file_storage_request;
