# STORAGE module properties
module.id=order
module.name=Order module
module.description=Handle users products orders
module.version=2.1.0
module.author=REGARDS
module.legalOwner=CNES
module.documentation=https://github.com/RegardsOss