server:
  port: 8888
spring:
  application:
    name: rs-configuration
  profiles: 
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/regards

info:
  id: ${spring.application.name}


