package fr.cnes.regards.modules.processing.entities;

import fr.cnes.regards.modules.processing.domain.execution.ExecutionStatus;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.domain.Persistable;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.OffsetDateTime;
import java.util.UUID;

@Data @With
@AllArgsConstructor @NoArgsConstructor
@Builder(toBuilder = true)

@Table("t_execution_step")
public class ExecutionStepEntity implements Persistable<Long> {

    /** Autogenerated long from sequence, to be able to order by it to have the correct sequence of steps in order. */
    @Id
    private Long id;

    @Column("execution_id")
    private UUID executionId;

    private ExecutionStatus status;

    @Column("time")
    private OffsetDateTime time;

    @Column("message")
    private String message;

    @Override public boolean isNew() {
        return id == null || id < 0;
    }
}
