#set( $semicolon = ':' )
#set( $dollar = '$' )
server:
  adress: localhost
  port: 3333

security:
  client: acme
  secret: acmesecret

spring:
  application:
    name : ${artifactId}
    
swagger:
  api:
    name: ${artifactId}-api

cloud:
  config:
    discovery:
      enabled: true
    server:
      enabled: false
      name: myconfigserver

 
