server:
  adress: localhost
  port: 7777


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  application:
    name : ${artifactId}
    
swagger:
  api:
    name: ${artifactId}-api

cloud:
  config:
    discovery:
      enabled: true
    server:
      enabled: false
      name: myconfigserver

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value}
  client:
    enabled: false
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
    
my:
  otherproperty: Config server not reached
 
