#set( $semicolon = ':' )
#set( $dollar = '$' )
server:
  adress: localhost
  port: 3333

security:
  client: acme
  secret: acmesecret

spring:
  application:
    name : ${artifactId}
    
swagger:
  api:
    name: ${artifactId}-api

cloud:
  config:
    discovery:
      enabled: true
    server:
      enabled: false
      name: myconfigserver

eureka:
  instance:
    instanceId: ${dollar}{spring.application.name}${dollar}${semicolon}${dollar}{spring.application.instance_id${dollar}${semicolon}${dollar}{random.value}}
  client:
    enabled: false
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
 
